name: Build Ghcr Image
on: 
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: run with tmate and vscode
        required: false
        default: false
jobs:
  build_image:
    runs-on: ubuntu-22.04
    permissions: write-all
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: ./.github/actions/free_disk_space

      - name: Prepare Environment
        run: |
          chmod +x ./scripts/*.sh
          ./scripts/prepare_environment.sh

      - name: Set Environment Variables
        run: |
          source ./scripts/set_env.sh

      - name: Download Source
        run: ./scripts/download_source.sh

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: mxschmitt/action-tmate@v3
        with:
          detached: true
          timeout-minutes: 5
      - uses: fawazahmed0/action-debug-vscode@main # touch continue

      - name: Build Image
        run: |
          find . -type d -name ".git" -exec rm -rf {} +
          docker build --build-arg FLUTTER_VERSION=${{ env.VERSION }} -t ghcr.io/alost/flutter-engine-compile:latest -f Copy_Dockerfile .

      - name: Push Image
        run: |
          docker push ghcr.io/alost/flutter-engine-compile:latest

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 2
      - uses: fawazahmed0/action-debug-vscode@main # touch continue
        if: ${{ failure() }}